export interface Review {
  id: number;
  name: string;
  rating: number;
  timeAgo: string;
  text: string;
  reviewerInfo?: string;
  ownerResponse?: string;
  ownerResponseTime?: string;
  tags?: string[];
  positive?: string[];
  services?: string[];
  priceAssessment?: string;
}

export const REVIEW_TAGS = [
  { label: 'All', count: 42 },
  { label: 'knowledgeable staff', count: 10 },
  { label: 'kind staff', count: 4 },
  { label: 'scheduling', count: 4 },
  { label: 'furnace repair', count: 3 },
  { label: 'clear communication', count: 3 },
  { label: 'clear explanations', count: 3 },
  { label: 'quality work', count: 3 },
  { label: 'immediate help', count: 2 },
  { label: 'trustworthy', count: 2 },
  { label: 'speed', count: 2 },
];

export const ALL_REVIEWS: Review[] = [
  {
    id: 1,
    name: 'Luke Hopper',
    rating: 5,
    timeAgo: '2 months ago',
    text: 'Needed a boiler inspection on a short notice and Alex fit us in and did a super professional job! We are out of state but communication was excellent and straightforward. Thank you again!',
    reviewerInfo: 'Local Guide · 82 reviews · 14 photos',
    tags: ['clear communication', 'scheduling'],
  },
  {
    id: 2,
    name: 'Jennifer Desmond',
    rating: 5,
    timeAgo: '8 months ago',
    text: "Alex with L&M Maintenance and Repair came out on a Saturday when my mom's heat went out and her regular company doesn't service evenings or weekends. He restored heat, addressed a few minor issues, and clearly explained what needed attention versus what could wait. His communication was thoughtful, honest, and compassionate, especially given my mom's age. I was very impressed with the professionalism and care and would absolutely call him again.",
    ownerResponse: "Thank you for this shining review! Above all else, we believe in quality customer service and I'm glad we met that mark. Thanks for your business!",
    ownerResponseTime: '8 months ago',
    tags: ['clear communication', 'kind staff', 'furnace repair'],
  },
  {
    id: 3,
    name: 'Joseph Kuta',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Alex at L & M is Mr. Clutch. I've called on his services professionally for many of my clients in Real Estate as well as within my own home & office. I recommend giving him a call today. 5 Stars",
    ownerResponse: "This means a lot, Joe. Knowing I have the confidence of such a well-known and respected member of our community is definitely a feather in my cap. I look forward to helping you in the future to come.",
    ownerResponseTime: 'a year ago',
    tags: ['knowledgeable staff', 'trustworthy'],
  },
  {
    id: 4,
    name: 'Tami Snowden',
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Alex is very good at what he does, very detailed with every available option. He is detailed and cares about your home. Communication is key which he does keep updated. I trust him to take care of any property without being there. I will only and always use him.\nThank You',
    ownerResponse: "Thank you taking the time to share your thoughts, Tami! I appreciate your business and find value in knowing you're satisfied with the work I've done and that I've earned the trust of you and your family!",
    ownerResponseTime: '2 years ago',
    positive: ['Responsiveness', 'Punctuality', 'Quality', 'Professionalism', 'Value'],
    services: ['Water heater installation', 'Water tank installation', 'Service not listed'],
    tags: ['clear communication', 'trustworthy', 'knowledgeable staff'],
  },
  {
    id: 5,
    name: 'Kim Williams',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'Alex was very professional. He replaced one of the toilets in our home. He cleaned up everything, worked very quickly and kept us informed before shutting off the water. I would highly recommend L&M for your home maintenance and repair needs.',
    ownerResponse: 'Thanks Kim! It was my pleasure, and I hope your new toilet suits your needs well! It was great meeting you!',
    ownerResponseTime: 'a year ago',
    tags: ['quality work', 'knowledgeable staff'],
  },
  {
    id: 6,
    name: 'Megan Stenhouse',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Alex was amazing. He came out right away when we had a Spicket issue, fix it in less than an hour. He's quick and efficient and knows what he's doing. I definitely would recommend him and will be using him again in the future.",
    ownerResponse: "Thanks Megan! It was nice meeting you and I look forward to assisting you in the future, should the need arise :)",
    ownerResponseTime: 'a year ago',
    tags: ['speed', 'knowledgeable staff'],
  },
  {
    id: 7,
    name: 'Kayla Turney',
    rating: 5,
    timeAgo: 'a year ago',
    text: "I had an irrigation and flooding emergency, Alex was able to fit me in for a same-day repair. He communicated clearly throughout the process, and offered very affordable pricing. What really stood out was the follow-up visit next day to make sure everything was still working properly. Very professional and reliable service. Highly recommend to everyone!",
    reviewerInfo: 'Local Guide · 2 reviews · 4 photos',
    ownerResponse: "Kayla- So glad to have met you; we think the same way about a lot of things! I'm glad got you fixed and running again, and I'm happy to help if you ever need me again!",
    ownerResponseTime: 'a year ago',
    tags: ['clear communication', 'scheduling', 'quality work'],
  },
  {
    id: 8,
    name: 'Krista Bryant',
    rating: 5,
    timeAgo: 'a year ago',
    text: "I'm thoroughly impressed with how fast he was able to get here, find the problem, and get it fixed. I've had two other plumbers here that put a \"bandaid\" on the problem, Alex came in and got the problem handled with in the matter of an hour and was able to troubleshoot problems the other guys didn't.\nTo top it off he was very patient and kind to my very curious 5 year old son.\nQuick, reliable, and kind.",
    ownerResponse: 'Thanks for this Krista. You have a beautiful family and your son made my day helping. Thanks for allowing me to earn your business.',
    ownerResponseTime: 'a year ago',
    tags: ['speed', 'kind staff', 'knowledgeable staff'],
  },
  {
    id: 9,
    name: 'Mike Durden',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Excellent, professional and personable. I reached out in a Sunday with a plumbing problem and Alex was able to get us on his schedule for the next day. Showed up when he said he would and did the work/ repairs in a timely manner. All around great experience and would recommend to anyone that needs work done. Overall great experience and highly recommend",
    ownerResponse: "Thanks for this, Mike! And thanks for being patient with me getting your repair done. I'm happy to help any time, should you decide to give me another shot :)",
    ownerResponseTime: 'a year ago',
    tags: ['scheduling', 'quality work'],
  },
  {
    id: 10,
    name: 'Misty White',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Our heater went out yesterday, so I reached out through Facebook for suggestions. Alex with L&M was one of the recommendations. I am so happy I called him because he was able to get us right into his schedule. He got us in right away and was here when he said he would be. I was working today when he came over, but my husband had nothing but good things to say about Alex. His prices are fair and reasonable. He is very friendly and knows what he is doing. We will be using him again because my husband is not physically able to do the things he used to because of his stroke. So, Alex, we will be getting more calls from us. Thank You so much for getting us taken care of so quickly, we appreciate your service.",
    ownerResponse: "Thanks for sharing this, Misty. I'm happy we were able to affordably and quickly get your furnace back up and running. I know the feeling you get when your heater goes out and it's 20 degrees outside, and I'm glad we resolved that for you! Should you need us in the future, we'll be at the ready to help!",
    ownerResponseTime: 'a year ago',
    tags: ['furnace repair', 'kind staff', 'scheduling'],
  },
  {
    id: 11,
    name: 'Lynda Jackson',
    rating: 5,
    timeAgo: 'a year ago',
    text: "We had a pipe burst in the afternoon that completely flooded the inside of our home. We called Alex from L&M repair. He came over right after finishing a job. It was after business hours but, he worked until he figured out where the leak was coming from and repaired it.\nHe was courteous & professional. His fee for the job was very reasonable. Especially since he came after hours.\nWe have already hired him again for another project.\nWe would highly recommend L&M.",
    ownerResponse: "Lynda, thanks for sharing this! No one wants to deal with plumbing issues but the delightful attitude you guys had despite, was more than refreshing. I'm glad we got your plumbing fixed up without touring to go the night without water! Thanks again!",
    ownerResponseTime: 'a year ago',
    tags: ['immediate help', 'knowledgeable staff'],
  },
  {
    id: 12,
    name: 'Mary & Greg Crider',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'Came out on a holiday weekend at 7pm at night capped out a broken valve so we could have water. Back the next day (Memorial Day) and repaired. Prompt, kind, courteous, and cleaned up. Very impressed and will definitely recommend his services. Thank you again for all you did for us.',
    ownerResponse: "Thanks for sharing this review! I'm glad we got your water on without further delay. Some issues just can't be fixed at the initial service call but we'll definitely do anything we can to lessen the impact on you! Thanks for your business.",
    ownerResponseTime: '8 months ago',
    priceAssessment: 'Great price',
    services: ['Shower repair'],
    tags: ['immediate help', 'kind staff'],
  },
  {
    id: 13,
    name: 'Jamison Trevan',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Alex is AMAZING! L&M has a customer for life! He is EXTREMELY knowledgeable and EXTREMELY friendly and I have used L&M on MULTIPLE occasions! Wouldn't trust anyone else to work on my irrigation system!",
    reviewerInfo: 'Local Guide · 12 reviews · 172 photos',
    ownerResponse: "Thanks Jamison! I appreciate your business AND the friendship we've struck up! God is good!",
    ownerResponseTime: 'a year ago',
    tags: ['knowledgeable staff'],
  },
  {
    id: 14,
    name: 'Kyle Fullerton',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Had the classic my children threw toys/wetnaps down the toilet and backed up my drainage system. Reached out to Alex and he told me he could get to me very quickly and he did! Fixed the problem at a very reasonable price! Now I can go back to taking showers in my own home. He will have my business for all future endeavors and issues.",
    ownerResponse: "I think every parent out there has one of these stories! Luckily it was a quick fix and the showers are running again 😁. Thank you for sharing your thoughts and thank you for your business!",
    ownerResponseTime: 'a year ago',
    tags: ['speed', 'scheduling'],
  },
  {
    id: 15,
    name: 'Marquita Gallegos',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Alex fits you in his schedule promptly and does quality work. I would refer him to anyone not wanting to pay an arm and a leg and to get the job done right! Thanks Alex!",
    reviewerInfo: 'Local Guide · 24 reviews',
    ownerResponse: "Thanks Marquita! Can't wait to see your kitchen transformation!",
    ownerResponseTime: 'a year ago',
    tags: ['quality work', 'scheduling'],
  },
  {
    id: 16,
    name: 'Kirsten McBeain',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Alex was incredible from start to finish! We have had him help us with multiple things and each time he is quick to find the solution- and is extremely educated! I would highly recommend him to anyone looking for an honest and reliable worker. Thank you so much for everything Alex!!",
    ownerResponse: "I am so incredibly blessed by you and your family, Kirsten. Thanks for sharing this. I'm Happy to have been of assistance and happy to help should you need me in the future! 😁",
    ownerResponseTime: 'a year ago',
    tags: ['knowledgeable staff', 'clear explanations'],
  },
  {
    id: 17,
    name: 'Tana S',
    rating: 5,
    timeAgo: '3 years ago',
    text: 'Alex is easy to work with. He gets back to you quickly. He is able to get into your home quickly. His prices are very reasonable. Alex is very knowledgeable about the products he is working on. I would highly recommend L&M Maintenance and Repair to my friends for their service needs.',
    ownerResponse: "Thanks for this review! You guys are truly an amazing couple and I admire your family. Thank you for giving me the opportunity to earn your business.",
    ownerResponseTime: '3 years ago',
    tags: ['knowledgeable staff'],
  },
  {
    id: 18,
    name: 'Lucas',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Super helpful. Detailed in explanation got what needed done fast and communicated WHAT exactly was going wrong and WHY the problem was occurring. He also fixed a couple things that weren't part of the main job, which is incredibly generous. 100% recommended for anyone that might feel overwhelmed with a project at home!",
    ownerResponse: 'Thanks Lucas! Glad we got you fixed up painlessly!',
    ownerResponseTime: 'a year ago',
    tags: ['clear explanations', 'knowledgeable staff'],
  },
  {
    id: 19,
    name: 'Madison Backes',
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Alex is professional, trustworthy, and provides high quality work! He is honest and fair. Alex does a variety of work and helps us manage our rental property giving us piece of mind. Highly recommend!',
    reviewerInfo: 'Local Guide · 13 reviews · 13 photos',
    ownerResponse: "Madi, thanks for taking the time to share a little about your experience! I'm excited to be a part of your rental venture and look forward to working with you in the years to come😀",
    ownerResponseTime: '2 years ago',
    tags: ['trustworthy', 'quality work'],
  },
  {
    id: 20,
    name: 'Susan Reeves',
    rating: 5,
    timeAgo: '2 years ago',
    text: "Alex was able to schedule an appointment with me the following day of my calling him. Very professional & efficient. He made some good suggestions to make my irrigation pump more user friendly! He is honest & fair.\nAnother's plus is the fact he's local!",
    ownerResponse: "Thank you for the great review! I'm pleased I could assist you quickly and provide useful suggestions for your irrigation system. Your support as a local client means a lot. I'm here whenever you need further help!",
    ownerResponseTime: '2 years ago',
    tags: ['scheduling', 'clear explanations'],
  },
  {
    id: 21,
    name: 'Shaun Freeburg',
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Alex took care of my furnace. And was very professional. He came when he said and was very thorough. He was also able to help me with some other issues. He is best Maintenance man I have found. I will be recommending him to all my friends.',
    tags: ['furnace repair', 'knowledgeable staff'],
  },
  {
    id: 22,
    name: 'Krista Trefiletti',
    rating: 1,
    timeAgo: 'a year ago',
    text: "Gave L&M a call because my AC unit stopped blowing cold air a few days ago. I got several recommendations for L&M which is why I decided to reach out. We spoke with Alex who was in the middle of another job but got our hopes up saying he could make it out that same day and that he'd call us back. An hour goes by and we don't hear from him (no big deal) so we decided to give him another call. No answer so we called again. Still no answer. So we sent a text and he responded apologizing saying he got tied down and asked us to go outside and check on a few things (which we did). We got no response and ultimately decided to go with someone else as an entire day (with no AC) was wasted waiting around for a call back. We were completely ghosted I guess. Extremely disappointed.",
    reviewerInfo: 'Local Guide · 77 reviews · 16 photos',
    ownerResponse: "Krista, my apologies. I was admitted into the hospital and unable to work. I understand your frustration and I'm very sorry this caused a delay in your repair and ultimately your discomfort. Should the opportunity arise, I'd be happy to make it up to you. To provide the best service possible, I have hired services to handle phone calls in the event I'm unable to. Thank your for your feedback. Take care",
    ownerResponseTime: 'a year ago',
  },
  {
    id: 23,
    name: 'Maggie Takeichi',
    rating: 5,
    timeAgo: '2 years ago',
    text: "Alex was able to come the day I called. He responded quickly, friendly and was able to help me with an outlet issue. He's local to Fruita and would definitely use him again for other issues since he does a wide range of maintenance and repairs.",
    reviewerInfo: 'Local Guide · 45 reviews · 37 photos',
    ownerResponse: "It was a pleasure meeting you, Maggie. I truly appreciate working with someone who values my time and expertise as much as you do. I'm excited to be your \"backup\" for any projects you'd rather not handle yourself—though with your ambition and DIY spirit, I know that won't be too often!",
    ownerResponseTime: '2 years ago',
    tags: ['scheduling', 'knowledgeable staff'],
  },
  {
    id: 24,
    name: 'Richie Romero',
    rating: 5,
    timeAgo: '3 years ago',
    text: "Alex owner of L&M Maintenance & Repair Was Awesome! He took my call around 8 pm Friday night.\nI had a situation with a tenant that had No hot water or heat! Alex made the repair in a timely manner and charged a very reasonable price for an after hour call!! I will continue to use L&M for my future plumbing needs!",
    tags: ['furnace repair', 'immediate help'],
  },
  {
    id: 25,
    name: 'Brooke Estridge',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'Alex was quick to respond made it to my home in less than 30 minutes. Figured out the issue fast and additionally helped service my AC and was very reasonably priced!',
    ownerResponse: "Thanks for sharing this, Brooke! With basic, consistent maintenance, like we did today, your system should last for years 😁 Thanks for entrusting L&M with your AC repair!",
    ownerResponseTime: 'a year ago',
    tags: ['speed', 'knowledgeable staff'],
  },
  {
    id: 26,
    name: 'Ericka Lider',
    rating: 5,
    timeAgo: '4 years ago',
    text: "Alex with L&M Maintenance and Repair is fantastic!! We first came across him on a holiday weekend when I accidentally broke a pipe trying to replace an old toilet! He was the only person willing to stop by to help me on a holiday and even tried talking me through how to fix it over the phone to save me some money, but I was already too discouraged to try and fix it myself after breaking a pipe over something that should have been simple. A few months later, we had a new issue with a pipe that had been leaking underneath my manufactured home. He was able to come over and fix the issue almost immediately and while he was down there he noticed a lot of my pipes needed to be replaced or we would have more issues in the future. He was able to get all of them replaced with some help by Ronzo (who was also very polite and professional) in the time frame of just a couple of days! We are more than thrilled we found such a trustworthy, down to earth and affordable plumber. We can 100% say if we have any other plumbing issues we will be calling him! 10/10 would highly recommend Alex!!!",
    ownerResponse: 'Thank you so much for this review. You are by far one of my most memorable customers and your business means a great deal to me.',
    ownerResponseTime: 'a year ago',
    tags: ['trustworthy', 'kind staff', 'knowledgeable staff'],
  },
  {
    id: 27,
    name: 'Jaime Saenz',
    rating: 5,
    timeAgo: '2 years ago',
    text: "We are so grateful for the service L&M provided us. Our furnace stopped working late on a Friday evening and after calling several \"24 hour\" companies to only be told we'd have to wait until Monday, L&M answered and was here within an hour! He wasted no time getting to work and got our heat back on within an hour. I can not stress how much of a relief this has been to us as we have young children in the home and were extremely worried about how we were going to stay warm through the weekend. Thank you so much for spending your Friday night helping our family.",
    ownerResponse: "THANK YOU for taking the time to share your thoughts! I very well understand the stress a parent faces in instances like this, and I'm relieved we were able to get the heat back up and running before it got too cold. You guys have a beautiful family! Thank you for allowing me the opportunity to earn your business.",
    ownerResponseTime: '2 years ago',
    tags: ['furnace repair', 'immediate help', 'kind staff'],
  },
  {
    id: 28,
    name: 'Sonja Carpenter',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'Easy to schedule. Showed up and did the work. Fair pricing. Easy payment option. All around great experience',
    ownerResponse: "Thanks for trusting L&M with your repair needs, Sonja! I'm glad it was a fairly easy fix!",
    ownerResponseTime: 'a year ago',
    tags: ['scheduling'],
  },
  {
    id: 29,
    name: 'Kerri Spore',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Very professional, timely and a pleasure to work with. Exceeded my expectations. I highly recommend!',
    tags: ['quality work'],
  },
  {
    id: 30,
    name: 'Barbara Schumacher',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'I had broken water pipes from the recent freeze and Alex came so quickly, fixed it quickly and charged a VERY fair and reasonable price!!!! He is my hero!',
    ownerResponse: 'Thank you for this Barb! So glad it was a quick fix!',
    ownerResponseTime: 'a year ago',
    tags: ['speed', 'immediate help'],
  },
  {
    id: 31,
    name: 'Carla Griffin',
    rating: 5,
    timeAgo: '3 years ago',
    text: 'Alex was Kind, courteous, and took the time to explain what he was doing. He was able to help us the same day we called. Thank you Alex, and L&M!',
    ownerResponse: "I'm happy we were able to resolve your issues in a timely manner. We understand how important it is to get things fixed when they break or stop working without delay. Thanks for trusting us to do so!",
    ownerResponseTime: 'a year ago',
    tags: ['clear explanations', 'kind staff'],
  },
  {
    id: 32,
    name: 'Taylor Young',
    rating: 5,
    timeAgo: 'a year ago',
    text: "Super friendly and helpful. He definitely knows his stuff and doesn't charge you an arm and a leg. I will definitely be returning with any future needs!",
    ownerResponse: "Hey Taylor! So glad we were able to get you fixed up quickly and affordably! Hopefully you won't but if you do, we're always just a phone call away! Thanks for your review!",
    ownerResponseTime: 'a year ago',
    tags: ['knowledgeable staff'],
  },
  {
    id: 33,
    name: 'Olivia',
    rating: 5,
    timeAgo: '2 years ago',
    text: "Alex was responsive, efficient, and friendly. He got the job done, and the price was very reasonable. He's the best!",
    reviewerInfo: 'Local Guide · 323 reviews · 274 photos',
    ownerResponse: "Thanks for sharing your thoughts! I'm happy we met your expectations. If you ever need us again, we're just a call away!",
    ownerResponseTime: 'a year ago',
    tags: ['quality work'],
  },
  {
    id: 34,
    name: 'Cheryl Paverud',
    rating: 5,
    timeAgo: '8 months ago',
    text: 'Very respectful and explained job completely. Would hire again.',
    reviewerInfo: 'Local Guide · 28 reviews',
    ownerResponse: 'Thanks, Cheryl! Happy to help!',
    ownerResponseTime: '8 months ago',
    tags: ['clear explanations'],
  },
  {
    id: 35,
    name: 'Desiree Wade',
    rating: 5,
    timeAgo: '3 years ago',
    text: 'Alex came and helped my salon with less than 24 hours and got us up and running again! Very professional and efficient! Highly recommend.',
    ownerResponse: "Thanks, Desiree! I appreciate your business!",
    ownerResponseTime: '3 years ago',
    tags: ['speed'],
  },
  {
    id: 36,
    name: 'Angel McBeain',
    rating: 5,
    timeAgo: '3 years ago',
    text: 'Alex was great to work with. His knowledge and attention to detail was very refreshing. Would highly recommend him.',
    ownerResponse: "I'm delighted to hear that you had a positive experience working with L&M Maintenance and Repair! Thank you for taking the time to share your feedback. We truly value your recommendation and look forward to any future opportunities to assist you.",
    ownerResponseTime: '2 years ago',
    positive: ['Quality', 'Value'],
    services: ['Plumbing leak detection'],
    tags: ['knowledgeable staff', 'quality work'],
  },
  {
    id: 37,
    name: 'Marlys Laugsand',
    rating: 5,
    timeAgo: '3 years ago',
    text: "L & M responded to my call within an hour. They allowed me to stay in my home by loaning me space heaters until they could get my new boiler and install it.",
    ownerResponse: "Thanks for sharing this, Marlys, and thank you for your continued business!",
    ownerResponseTime: '8 months ago',
    tags: ['furnace repair', 'kind staff'],
  },
  {
    id: 38,
    name: 'Connor Stocks',
    rating: 5,
    timeAgo: '3 years ago',
    text: "Can do just about anything you ask. Had my furnace go out and he came over and had it fixed quick so me and my family wouldn't freeze through the winter. 10/10 recommend this business",
    ownerResponse: "Thanks, Connor. I'm glad you guys are warm for the winter!",
    ownerResponseTime: '3 years ago',
    tags: ['furnace repair', 'knowledgeable staff'],
  },
  {
    id: 39,
    name: 'Annie LeVan',
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Great work, fair prices, would recommend him and have many times',
    ownerResponse: "Thank you for your positive feedback and recommendations! I'm glad you were happy with the work and pricing. Your support is greatly appreciated.",
    ownerResponseTime: '2 years ago',
    tags: ['quality work'],
  },
  {
    id: 40,
    name: 'Melyssa Meier',
    rating: 5,
    timeAgo: 'a year ago',
    text: 'Very timely response and was able to help us right away. Would highly recommend!',
    ownerResponse: "Thanks for sharing this, Melyssa! I'm happy we got you up and working again!",
    ownerResponseTime: 'a year ago',
    tags: ['speed'],
  },
  {
    id: 41,
    name: 'Hannah Edwards',
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Quick and personable! Happy to have our fan fixed.',
    ownerResponse: "Hannah, we're so glad to hear you had a good experience with our services! It's always a treat when everything goes according to plan in a timely manner! If you need repair services in the future, we're more than happy to help!",
    ownerResponseTime: '2 years ago',
    tags: ['speed'],
  },
  {
    id: 42,
    name: 'Chantelle Kilpatrick',
    rating: 1,
    timeAgo: '2 months ago',
    text: "Avoid at all cost! Was quoted for a two day job for my living room decorated. Day 1 started at 8.30am and finished at 5 and had only lined one wall. Stole my door key and helped himself to 400 pound as well as my living room wall paper. Apparently needed to take the role home to read instructions? The firm is run by Mick Lofthouse and his employed decorator he sends out to work is Carl Smith. When he did arrive with my belongings he only has 200 pound of my money! He stunk of booze. I had to wait another 2 hours for my remaining 200 pound to be given as I was told it would be Tuesday until I had a family member involved.",
  },
];
